"""user_sport table (M2·B19)

Новая таблица-связка user_sport(user_id, sport_id, current_level_id?, rating?, joined_at)
с составным PK (user_id, sport_id) и FK на user.id и sport.id. Дисциплины, которые ведёт
пользователь (link/unlink через /me/sports). current_level_id — nullable int без FK
(таблицы уровней пока нет). Свежая таблица — обычный create_table/drop_table.

Revision ID: 162efaa3629d
Revises: bd6e5463a427
Create Date: 2026-06-25 08:28:51.259604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel-типы (AutoString и пр.) в autogenerate-миграциях


# revision identifiers, used by Alembic.
revision: str = '162efaa3629d'
down_revision: Union[str, Sequence[str], None] = 'bd6e5463a427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sport',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('current_level_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'sport_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_sport')
    # ### end Alembic commands ###
