"""sponsor table M6·B29

Новая таблица sponsor(id, name, description, url, logo_path) — самостоятельный
каталог спонсоров без FK и без user-скоупа. name уникален (unique index).
Свежая таблица — обычный create_table/drop_table.

Revision ID: c3492fe0b4d2
Revises: cf4bbee8057d
Create Date: 2026-06-25 16:28:34.073033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel-типы (AutoString и пр.) в autogenerate-миграциях


# revision identifiers, used by Alembic.
revision: str = 'c3492fe0b4d2'
down_revision: Union[str, Sequence[str], None] = 'cf4bbee8057d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sponsor_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sponsor_name'))

    op.drop_table('sponsor')
    # ### end Alembic commands ###
