"""baseline schema

Revision ID: c78441d536ea
Revises: 
Create Date: 2026-06-21 05:29:18.590750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel-типы (AutoString и пр.) в autogenerate-миграциях


# revision identifiers, used by Alembic.
revision: str = 'c78441d536ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_day',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_kcal', sa.Integer(), nullable=True),
    sa.Column('active_kcal', sa.Integer(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('moving_min', sa.Integer(), nullable=True),
    sa.Column('idle_min', sa.Integer(), nullable=True),
    sa.Column('warmup_min', sa.Integer(), nullable=True),
    sa.Column('active_met', sa.Integer(), nullable=True),
    sa.Column('intense_met', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('source_image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('body_measurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('belly_cm', sa.Float(), nullable=True),
    sa.Column('calf_l_cm', sa.Float(), nullable=True),
    sa.Column('calf_r_cm', sa.Float(), nullable=True),
    sa.Column('chest_cm', sa.Float(), nullable=True),
    sa.Column('shoulders_cm', sa.Float(), nullable=True),
    sa.Column('biceps_l_cm', sa.Float(), nullable=True),
    sa.Column('biceps_r_cm', sa.Float(), nullable=True),
    sa.Column('glutes_cm', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('body_measurement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_body_measurement_date'), ['date'], unique=False)

    op.create_table('deficit_day',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('eaten_kcal', sa.Integer(), nullable=True),
    sa.Column('burn_kcal', sa.Integer(), nullable=True),
    sa.Column('deficit_kcal', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('food_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('portion_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('portion_grams', sa.Float(), nullable=True),
    sa.Column('kcal', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('carb_g', sa.Float(), nullable=True),
    sa.Column('import_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_entry_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_entry_import_id'), ['import_id'], unique=False)

    op.create_table('hr_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('zones_json', sa.JSON(), nullable=True),
    sa.Column('source_image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hr_zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hr_zones_date'), ['date'], unique=False)

    op.create_table('inbody_measurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('muscle_mass_kg', sa.Float(), nullable=True),
    sa.Column('visceral_fat', sa.Float(), nullable=True),
    sa.Column('water', sa.Float(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('source_image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inbody_measurement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inbody_measurement_date'), ['date'], unique=False)

    op.create_table('smart_goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('target_body_fat_pct', sa.Float(), nullable=True),
    sa.Column('target_measurements_json', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('baseline_json', sa.JSON(), nullable=True),
    sa.Column('why_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('smart_goal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_smart_goal_status'), ['status'], unique=False)

    op.create_table('sport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sport', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sport_name'), ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievement_sport_id'), ['sport_id'], unique=False)

    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_sport_id'), ['sport_id'], unique=False)

    op.create_table('recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('raw_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['smart_goal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_goal_id'), ['goal_id'], unique=False)

    op.create_table('workout_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_session_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_session_sport_id'), ['sport_id'], unique=False)

    op.create_table('achievement_proof',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('video_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thumbnail_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achievement_proof', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievement_proof_achievement_id'), ['achievement_id'], unique=False)

    op.create_table('cardio_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('duration_min', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('avg_pace', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['workout_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cardio_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cardio_log_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cardio_log_session_id'), ['session_id'], unique=False)

    op.create_table('personal_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personal_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personal_record_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_personal_record_exercise_id'), ['exercise_id'], unique=False)

    op.create_table('skill_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('hold_sec', sa.Float(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('quality', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['workout_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skill_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_log_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_log_session_id'), ['session_id'], unique=False)

    op.create_table('strength_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_index', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['workout_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strength_set', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strength_set_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strength_set_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strength_set', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strength_set_session_id'))
        batch_op.drop_index(batch_op.f('ix_strength_set_exercise_id'))

    op.drop_table('strength_set')
    with op.batch_alter_table('skill_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_log_session_id'))
        batch_op.drop_index(batch_op.f('ix_skill_log_exercise_id'))

    op.drop_table('skill_log')
    with op.batch_alter_table('personal_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personal_record_exercise_id'))
        batch_op.drop_index(batch_op.f('ix_personal_record_date'))

    op.drop_table('personal_record')
    with op.batch_alter_table('cardio_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cardio_log_session_id'))
        batch_op.drop_index(batch_op.f('ix_cardio_log_exercise_id'))

    op.drop_table('cardio_log')
    with op.batch_alter_table('achievement_proof', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievement_proof_achievement_id'))

    op.drop_table('achievement_proof')
    with op.batch_alter_table('workout_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_session_sport_id'))
        batch_op.drop_index(batch_op.f('ix_workout_session_date'))

    op.drop_table('workout_session')
    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_goal_id'))

    op.drop_table('recommendation')
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_sport_id'))

    op.drop_table('exercise')
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievement_sport_id'))

    op.drop_table('achievement')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('sport', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sport_name'))

    op.drop_table('sport')
    with op.batch_alter_table('smart_goal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_smart_goal_status'))

    op.drop_table('smart_goal')
    with op.batch_alter_table('inbody_measurement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inbody_measurement_date'))

    op.drop_table('inbody_measurement')
    with op.batch_alter_table('hr_zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hr_zones_date'))

    op.drop_table('hr_zones')
    with op.batch_alter_table('food_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_entry_import_id'))
        batch_op.drop_index(batch_op.f('ix_food_entry_date'))

    op.drop_table('food_entry')
    op.drop_table('deficit_day')
    with op.batch_alter_table('body_measurement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_body_measurement_date'))

    op.drop_table('body_measurement')
    op.drop_table('activity_day')
    # ### end Alembic commands ###
