"""sport_recommendation table M5·B26

Новая таблица sport_recommendation(id, sport_id, from_level_id, to_level_id,
title, body) — рекомендации/гайды по виду спорта. FK sport_id на sport.id;
from_level_id/to_level_id — необязательные FK на sport_level.id (переход между
ступенями). title/body обязательны. Глобальный каталог без user-скоупа.
Свежая таблица — обычный create_table/drop_table.

Revision ID: cf4bbee8057d
Revises: e8bea30216db
Create Date: 2026-06-25 14:19:12.522337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel-типы (AutoString и пр.) в autogenerate-миграциях


# revision identifiers, used by Alembic.
revision: str = 'cf4bbee8057d'
down_revision: Union[str, Sequence[str], None] = 'e8bea30216db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sport_recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('from_level_id', sa.Integer(), nullable=True),
    sa.Column('to_level_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['from_level_id'], ['sport_level.id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], ),
    sa.ForeignKeyConstraint(['to_level_id'], ['sport_level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sport_recommendation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sport_recommendation_sport_id'), ['sport_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sport_recommendation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sport_recommendation_sport_id'))

    op.drop_table('sport_recommendation')
    # ### end Alembic commands ###
