"""sport_mentor table M5·B25

Новая таблица sport_mentor(id, sport_id, name, bio, contact, url, photo_path) —
наставники/тренеры по виду спорта. FK на sport.id. name обязателен;
bio/contact/url/photo_path необязательны. Глобальный каталог без user-скоупа.
Свежая таблица — обычный create_table/drop_table.

Revision ID: e8bea30216db
Revises: a4c7e1b9d350
Create Date: 2026-06-25 14:03:28.927142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel-типы (AutoString и пр.) в autogenerate-миграциях


# revision identifiers, used by Alembic.
revision: str = 'e8bea30216db'
down_revision: Union[str, Sequence[str], None] = 'a4c7e1b9d350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sport_mentor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photo_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sport_mentor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sport_mentor_sport_id'), ['sport_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sport_mentor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sport_mentor_sport_id'))

    op.drop_table('sport_mentor')
    # ### end Alembic commands ###
